# Generated by Django 4.2.5 on 2025-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=177540265759719733427720058383964155306, unique=True),
        ),
    ]
