# Generated by Django 4.2.5 on 2025-03-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=185294718597882398555761498010785868186, unique=True),
        ),
    ]
