# Generated by Django 4.2.5 on 2025-10-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_alter_user_fidc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fidc',
            field=models.UUIDField(default=56037170810026393503440142960446399467, unique=True),
        ),
    ]
